<?php

/**
 * Implement hook menu
 */
function heineken_bug_ranking_menu() {
  $items = array(); 
  $items['admin/config/heineken_bug_ranking'] = array(
    'title'            => 'Heineken Bug Ranking',
    'description'      => 'Setting for Heineken Bug Ranking',
    'page callback'    => 'system_admin_menu_block_page',
    'page arguments'   => array( 'heineken_bug_ranking_admin_form' ),
    'access arguments' => array( 'administer heineken_bug_ranking' ),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'system.admin.inc',
    'file path'        => drupal_get_path( 'module', 'system' )
  );
  
  $items['admin/config/heineken_bug_ranking/users'] = array(
    'title'            => 'Users administration',
    'description'      => 'Add, remove, update users',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array( 'heineken_bug_ranking_admin_form' ),
    'access arguments' => array( 'administer heineken_bug_ranking' ),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'inc/user.admin.inc'
  );

  $items['admin/config/heineken_bug_ranking/project'] = array(
    'title'            => 'Projects administration',
    'description'      => 'Add, remove, update Projects',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array( 'heineken_bug_ranking_admin_form' ),
    'access arguments' => array( 'administer heineken_bug_ranking' ),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'inc/project.admin.inc'
  );

  $items['admin/config/heineken_bug_ranking/type'] = array(
    'title'            => 'Type administration',
    'description'      => 'Add, remove, update type bugs',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array( 'heineken_bug_ranking_admin_form' ),
    'access arguments' => array( 'administer heineken_bug_ranking' ),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'inc/type.admin.inc'
  );
  
  return $items;
}

